language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-geckoboard.gemspec
- gem install sensu-plugins-geckoboard-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: I4ON34PFyTeSck12tFjyIekrgCMqJgjoH4WKsxgx+UoXhAg9lZuBHjcVEZHIgSy/xUcpz3UM++toHb0CcYGkuUUYGn0O48U25gUOL/V8UrUWrMRNsvcxNA4N09hED6TJQQ7NQBxGYtZ2rJtSP5+iW5SDZQO3NzVS9Dc5orzxBZA=
  gem: sensu-plugins-geckoboard
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-geckoboard
